### YamlMime:PythonClass
uid: azure.iot.device.exceptions.NoConnectionError
name: NoConnectionError
fullName: azure.iot.device.exceptions.NoConnectionError
module: azure.iot.device.exceptions
inheritances:
- azure.iot.device.exceptions.ClientError
summary: Operation could not be completed because no connection has been established
constructor:
  syntax: NoConnectionError()
methods:
- uid: azure.iot.device.exceptions.NoConnectionError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.iot.device.exceptions.NoConnectionError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.iot.device.exceptions.NoConnectionError.args
  name: args
