### YamlMime:PythonClass
uid: azure.security.attestation.AttestationTokenValidationException
name: AttestationTokenValidationException
fullName: azure.security.attestation.AttestationTokenValidationException
module: azure.security.attestation
inheritances:
- builtins.ValueError
summary: Thrown when an attestation token validation fails.
constructor:
  syntax: AttestationTokenValidationException(message)
  parameters:
  - name: message
    description: Message for caller describing the reason for the failure.
    isRequired: true
    types:
    - <xref:str>
methods:
- uid: azure.security.attestation.AttestationTokenValidationException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.security.attestation.AttestationTokenValidationException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.security.attestation.AttestationTokenValidationException.args
  name: args
