### YamlMime:PythonClass
uid: azure.synapse.models.ErrorResponseException
name: ErrorResponseException
fullName: azure.synapse.models.ErrorResponseException
module: azure.synapse.models
inheritances:
- azure.core.exceptions.HttpResponseError
summary: 'Server responded with exception of type: ''ErrorResponse''.'
constructor:
  syntax: ErrorResponseException(response, error_model)
  parameters:
  - name: response
    description: Server response to be deserialized.
    isRequired: true
  - name: error_model
    description: A deserialized model of the response body as model.
    isRequired: true
methods:
- uid: azure.synapse.models.ErrorResponseException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.synapse.models.ErrorResponseException.from_response
  name: from_response
  summary: Deserialize this response as this exception, or a subclass of this exception.
  signature: from_response(response, deserialize)
  parameters:
  - name: response
    description: Server response to be deserialized.
    isRequired: true
  - name: deserialize
    description: A deserializer
    isRequired: true
- uid: azure.synapse.models.ErrorResponseException.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    *Deprecated since version 1.22.0:* This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback() -> None
- uid: azure.synapse.models.ErrorResponseException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.synapse.models.ErrorResponseException.args
  name: args
