### YamlMime:PythonClass
uid: corehttp.exceptions.ClientAuthenticationError
name: ClientAuthenticationError
fullName: corehttp.exceptions.ClientAuthenticationError
module: corehttp.exceptions
inheritances:
- corehttp.exceptions.HttpResponseError
summary: 'An error response with status code 4xx.

  This will not be raised directly by the core pipeline.'
constructor:
  syntax: 'ClientAuthenticationError(message: object | None = None, response: _HttpResponseCommonAPI
    | None = None, **kwargs: Any)'
  parameters:
  - name: message
    defaultValue: None
  - name: response
    defaultValue: None
methods:
- uid: corehttp.exceptions.ClientAuthenticationError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: corehttp.exceptions.ClientAuthenticationError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: corehttp.exceptions.ClientAuthenticationError.args
  name: args
- uid: corehttp.exceptions.ClientAuthenticationError.continuation_token
  name: continuation_token
  signature: 'continuation_token: str | None'
- uid: corehttp.exceptions.ClientAuthenticationError.exc_msg
  name: exc_msg
  signature: 'exc_msg: str'
- uid: corehttp.exceptions.ClientAuthenticationError.exc_traceback
  name: exc_traceback
  signature: 'exc_traceback: TracebackType | None'
- uid: corehttp.exceptions.ClientAuthenticationError.exc_type
  name: exc_type
  signature: 'exc_type: Type[Any] | None'
- uid: corehttp.exceptions.ClientAuthenticationError.exc_value
  name: exc_value
  signature: 'exc_value: BaseException | None'
- uid: corehttp.exceptions.ClientAuthenticationError.inner_exception
  name: inner_exception
  signature: 'inner_exception: BaseException | None'
- uid: corehttp.exceptions.ClientAuthenticationError.message
  name: message
  signature: 'message: str'
