### YamlMime:PythonClass
uid: azure.servicefabric.models.TestErrorChaosEvent
name: TestErrorChaosEvent
fullName: azure.servicefabric.models.TestErrorChaosEvent
module: azure.servicefabric.models
inheritances:
- azure.servicefabric.models._models_py3.ChaosEvent
summary: "Describes a Chaos event that gets generated when an unexpected event occurs\n\
  in the Chaos engine.\nFor example, due to the cluster snapshot being inconsistent,\
  \ while faulting\nan entity, Chaos found that the entity was already faulted \u2013\
  \ which would\nbe an unexpected event.\n\nAll required parameters must be populated\
  \ in order to send to Azure."
constructor:
  syntax: 'TestErrorChaosEvent(*, time_stamp_utc, reason: Optional[str] = None, **kwargs)
    -> None'
  parameters:
  - name: time_stamp_utc
    description: 'Required. The UTC timestamp when this Chaos event

      was generated.'
    isRequired: true
    types:
    - <xref:datetime>
  - name: kind
    description: Required. Constant filled by server.
    isRequired: true
    types:
    - <xref:str>
  - name: reason
    description: 'Describes why TestErrorChaosEvent was generated. For

      example, Chaos tries to fault a partition but finds that the partition is

      no longer fault tolerant, then a TestErrorEvent gets generated with the

      reason stating that the partition is not fault tolerant.'
    isRequired: true
    types:
    - <xref:str>
