### YamlMime:PythonEnum
uid: azure.mgmt.cosmosdb.models.ConnectionState
name: ConnectionState
fullName: azure.mgmt.cosmosdb.models.ConnectionState
summary: The kind of connection error that occurred.
module: azure.mgmt.cosmosdb.models
constructor:
  syntax: ConnectionState(value)
inheritances:
- builtins.str
- enum.Enum
fields:
- name: DATACENTER_TO_DATACENTER_NETWORK_ERROR
  uid: azure.mgmt.cosmosdb.models.ConnectionState.DATACENTER_TO_DATACENTER_NETWORK_ERROR
- name: INTERNAL_ERROR
  uid: azure.mgmt.cosmosdb.models.ConnectionState.INTERNAL_ERROR
- name: INTERNAL_OPERATOR_TO_DATA_CENTER_CERTIFICATE_ERROR
  uid: azure.mgmt.cosmosdb.models.ConnectionState.INTERNAL_OPERATOR_TO_DATA_CENTER_CERTIFICATE_ERROR
- name: OK
  uid: azure.mgmt.cosmosdb.models.ConnectionState.OK
- name: OPERATOR_TO_DATA_CENTER_NETWORK_ERROR
  uid: azure.mgmt.cosmosdb.models.ConnectionState.OPERATOR_TO_DATA_CENTER_NETWORK_ERROR
- name: UNKNOWN
  uid: azure.mgmt.cosmosdb.models.ConnectionState.UNKNOWN
