### YamlMime:PythonClass
uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError
name: RequiredLocalArtifactsNotFoundError
fullName: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError
module: azure.ai.ml.exceptions
inheritances:
- azure.ai.ml.exceptions.MlException
summary: Exception raised when local artifact is not provided for local endpoint.
constructor:
  syntax: 'RequiredLocalArtifactsNotFoundError(endpoint_name: str, required_artifact:
    str, required_artifact_type: str, deployment_name: str | None = None, error_category=''UserError'')'
  parameters:
  - name: endpoint_name
    isRequired: true
  - name: required_artifact
    isRequired: true
  - name: required_artifact_type
    isRequired: true
  - name: deployment_name
    defaultValue: None
  - name: error_category
    defaultValue: UserError
methods:
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.raise_with_traceback
  name: raise_with_traceback
  summary: 'Raise the exception with the existing traceback.


    *Deprecated since version 1.22.0:* This method is deprecated as we don''t support
    Python 2 anymore. Use raise/from instead.'
  signature: raise_with_traceback() -> None
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.args
  name: args
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.error_category
  name: error_category
  summary: Return the error category.
  return:
    description: The error category.
    types:
    - <xref:azure.ai.ml.exceptions.ErrorCategory>
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.no_personal_data_message
  name: no_personal_data_message
  summary: Return the error message with no personal data.
  return:
    description: No personal data error message.
    types:
    - <xref:str>
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.target
  name: target
  summary: Return the error target.
  return:
    description: The error target.
    types:
    - <xref:azure.ai.ml.exceptions.ErrorTarget>
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.continuation_token
  name: continuation_token
  signature: 'continuation_token: str | None'
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.exc_msg
  name: exc_msg
  signature: 'exc_msg: str'
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.exc_traceback
  name: exc_traceback
  signature: 'exc_traceback: TracebackType | None'
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.exc_type
  name: exc_type
  signature: 'exc_type: Type[Any] | None'
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.exc_value
  name: exc_value
  signature: 'exc_value: BaseException | None'
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.inner_exception
  name: inner_exception
  signature: 'inner_exception: BaseException | None'
- uid: azure.ai.ml.exceptions.RequiredLocalArtifactsNotFoundError.message
  name: message
  signature: 'message: str'
