### YamlMime:UniversalReference
api_name: []
items:
- children:
  - azure.core.exceptions.AzureError.raise_with_traceback
  class: azure.core.exceptions.AzureError
  fullName: azure.core.exceptions.AzureError
  inheritance:
  - inheritance:
    - inheritance:
      - type: builtins.object
      type: builtins.BaseException
    type: builtins.Exception
  langs:
  - python
  module: azure.core.exceptions
  name: AzureError
  summary: Base exception for all errors.
  syntax:
    content: AzureError(message, *args, **kwargs)
    parameters:
    - description: The message object stringified as 'message' attribute
      id: message
    - description: The original exception if any
      id: error
      type:
      - Exception
    variables:
    - description: The exception passed with the 'error' kwarg
      id: inner_exception
    - description: The exc_type from sys.exc_info()
      id: exc_type
    - description: The exc_value from sys.exc_info()
      id: exc_value
    - description: The exc_traceback from sys.exc_info()
      id: exc_traceback
    - description: A string formatting of message parameter, exc_type and exc_value
      id: exc_msg
    - description: A stringified version of the message parameter
      id: message
      type:
      - str
  type: class
  uid: azure.core.exceptions.AzureError
- class: azure.core.exceptions.AzureError
  fullName: azure.core.exceptions.AzureError.raise_with_traceback
  langs:
  - python
  module: azure.core.exceptions
  name: raise_with_traceback()
  namewithoutparameters: raise_with_traceback
  syntax:
    content: raise_with_traceback()
    parameters: []
  type: method
  uid: azure.core.exceptions.AzureError.raise_with_traceback
references:
- fullName: azure.core.exceptions.AzureError.raise_with_traceback
  isExternal: false
  name: raise_with_traceback()
  parent: azure.core.exceptions.AzureError
  uid: azure.core.exceptions.AzureError.raise_with_traceback
