### YamlMime:PythonClass
uid: azure.batch.custom.custom_errors.CreateTasksErrorException
name: CreateTasksErrorException
fullName: azure.batch.custom.custom_errors.CreateTasksErrorException
module: azure.batch.custom.custom_errors
inheritances:
- builtins.Exception
summary: Aggregate Exception containing details for any failures from a task add operation.
constructor:
  syntax: CreateTasksErrorException(pending_tasks=None, failure_tasks=None, errors=None)
  parameters:
  - name: message
    description: Error message describing exit reason
    isRequired: true
    types:
    - <xref:str>
  - name: pending_tasks
    description: List of tasks remaining to be submitted.
    defaultValue: None
    types:
    - '[<xref:TaskAddParameter>]'
  - name: failure_tasks
    description: List of tasks which failed to add
    defaultValue: None
    types:
    - '[<xref:TaskAddResult>]'
  - name: errors
    description: List of unknown errors forcing early termination
    defaultValue: None
    types:
    - '[<xref:Exception>]'
methods:
- uid: azure.batch.custom.custom_errors.CreateTasksErrorException.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.batch.custom.custom_errors.CreateTasksErrorException.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.batch.custom.custom_errors.CreateTasksErrorException.args
  name: args
